import type { Card } from '../types';
import { CardType, HeroClass } from '../types';

export const heroRegistry: Card[] = [
  {
    id: 'hero-001',
    name: 'Greedy Cheeks',
    type: CardType.Hero,
    heroClass: HeroClass.Bard,
    description: 'Draw 2 cards.',
    requirements: [{ type: 'point', value: 6 }],
    effect: [{
      action: 'DRAW',
      amount: 2,
    }],
    imagePath: '/api/images/heroes/bard_greedy_cheeks.png',
  },
  {
    id: 'hero-002',
    name: 'Dogy Dealer',
    type: CardType.Hero,
    heroClass: HeroClass.Bard,
    description: 'Exchange cards with another player.',
    requirements: [{ type: 'point', value: 5 }],
    effect: [{
      action: 'EXCHANGE',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/bard_dogy_dealer.png',
  },
  {
    id: 'hero-003',
    name: 'Mellow Dee',
    type: CardType.Hero,
    heroClass: HeroClass.Bard,
    description: 'Peaceful ability.',
    requirements: [{ type: 'point', value: 4 }],
    effect: [{
      action: 'CALM',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/bard_mellow_dee.png',
  },
  {
    id: 'hero-004',
    name: 'Tipsy Tootie',
    type: CardType.Hero,
    heroClass: HeroClass.Bard,
    description: 'Random card effect.',
    requirements: [{ type: 'point', value: 6 }],
    effect: [{
      action: 'RANDOM',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/bard_tipsy_tootie.png',
  },
  {
    id: 'hero-005',
    name: 'Buttons',
    type: CardType.Hero,
    heroClass: HeroClass.Wizard,
    description: 'Magic spell effect.',
    requirements: [{ type: 'point', value: 7 }],
    effect: [{
      action: 'SPELL',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/wizard_buttons.png',
  },
  {
    id: 'hero-006',
    name: 'Fluffy',
    type: CardType.Hero,
    heroClass: HeroClass.Wizard,
    description: 'Teleportation magic.',
    requirements: [{ type: 'point', value: 6 }],
    effect: [{
      action: 'TELEPORT',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/wizard_fluffy.png',
  },
  {
    id: 'hero-007',
    name: 'Hopper',
    type: CardType.Hero,
    heroClass: HeroClass.Wizard,
    description: 'Jump between dimensions.',
    requirements: [{ type: 'point', value: 8 }],
    effect: [{
      action: 'DIMENSION_JUMP',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/wizard_hopper.png',
  },
  {
    id: 'hero-008',
    name: 'Snowball',
    type: CardType.Hero,
    heroClass: HeroClass.Wizard,
    description: 'Ice magic ability.',
    requirements: [{ type: 'point', value: 5 }],
    effect: [{
      action: 'FREEZE',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/wizard_snowball.png',
  },
  {
    id: 'hero-009',
    name: 'Spooky',
    type: CardType.Hero,
    heroClass: HeroClass.Wizard,
    description: 'Dark magic spell.',
    requirements: [{ type: 'point', value: 7 }],
    effect: [{
      action: 'DARK_MAGIC',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/wizard_spooky.png',
  },
  {
    id: 'hero-010',
    name: 'Whiskers',
    type: CardType.Hero,
    heroClass: HeroClass.Wizard,
    description: 'Transform magic.',
    requirements: [{ type: 'point', value: 6 }],
    effect: [{
      action: 'TRANSFORM',
      amount: 1,
    }],
    imagePath: '/api/images/heroes/wizard_whiskers.png',
  },
  // Original heroes without images
  {
    id: 'hero-011',
    name: 'Bad Axe',
    type: CardType.Hero,
    heroClass: HeroClass.Fighter,
    description: 'Destroy a Hero card.',
    requirements: [{ type: 'point', value: 8 }],
    effect: [{
      action: 'DESTROY',
      amount: 1,
      cardType: CardType.Hero,
    }],
  },
  {
    id: 'hero-012',
    name: 'Kit Napper',
    type: CardType.Hero,
    heroClass: HeroClass.Thief,
    description: 'Steal a Hero card.',
    requirements: [{ type: 'point', value: 7 }],
    effect: [{
      action: 'STEAL',
      amount: 1,
      cardType: CardType.Hero,
    }],
  },
];
