import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Patua_One, Open_Sans } from "next/font/google";
import "./globals.css";
import { BlurProvider } from "../contexts/blur-context";
import { SizingProvider } from "../contexts/sizing-context";
import { CardOriginSizingProvider } from "../contexts/card-origin-sizing-context";
import { SoundProvider } from "../contexts/sound-context";
import { UserProvider } from "../contexts/user-context";
import { BlurOverlay } from "../components/blur-overlay";
import { ThemeProvider } from "next-themes";
import { getServerUserData } from "../lib/server-user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const patuaOne = Patua_One({
  variable: "--font-patua-one",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch user data at root level
  const initialUser = await getServerUserData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${patuaOne.variable} ${openSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider initialUser={initialUser.playerId ? initialUser : null}>
            <SoundProvider>
              <BlurProvider>
                <SizingProvider>
                  <CardOriginSizingProvider>
                    {children}
                    <BlurOverlay />
                  </CardOriginSizingProvider>
                </SizingProvider>
              </BlurProvider>
            </SoundProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
